# Generated by Django 4.0.2 on 2022-05-15 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_rename_id_producto_producto_idproducto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='comentario',
            name='Producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.producto'),
        ),
    ]
