# Generated by Django 4.0.2 on 2022-05-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_remove_producto_comentarios_comentario_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='pagina/imagenes/'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='imagen',
            field=models.ImageField(null=True, upload_to='pagina/imagenes/'),
        ),
    ]
