# Generated by Django 4.0.2 on 2022-05-16 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0007_producto_imagen_tienda_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tienda',
            options={'verbose_name': 'tienda', 'verbose_name_plural': 'tiendas'},
        ),
    ]
